services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -proot || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  php:
    build:
      context: ./docker/php
    environment:
      APP_ENV: dev
      DATABASE_URL: "mysql://symfony:symfony@db:3306/symfony?charset=utf8mb4"
    volumes:
      - ./app:/var/www/html
      - composer_cache:/tmp/composer
    depends_on:
      db:
        condition: service_healthy

  web:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    volumes:
      - ./app/public:/var/www/html/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

volumes:
  db_data:
  composer_cache:
